lib/signed-xml.js, test/signature-unit-tests.js
this PR adds the following features:
- `computeSignature` now accepts a options object for specify **location, prefix and custom attributes** for the signature
- Ability to add **custom attributes** to the generated signature
My use case is generate something like the following document ->
with this: 
```js
signer.computeSignature(xml, {
prefix: 'ds',
attrs: {
Id: 'signatureKG'
// ... more attrs here ..
}
});
```
- Ability to **specify the location of the signature based on a reference node** (defaults to append the signature in the root node)
For example, this code signs the `<repository>` node and adds the signature **after** the `<name>` node
```js
var xml = "<root><name>xml-crypto</name><repository>github</repository></root>"
var sig = new SignedXml()
sig.signingKey = …
```
=> Custom location and ability to add custom attributes to the signature

lib/signed-xml.js, test/saml-response-test.js, test/signature-integration-tests.js, test/signature-unit-tests.js
@bjrmatos @yaronn Here is what I was referring to in #59. This allows `loadSignature` to accept a DOM node or XML string, keeping backwards compatibility. The only possible breaking change would be if a caller was using `signatureXmlDoc` but I would think that should be regarded as private.
Thoughts?
=> Switch loadSignature to accept string or XML node

lib/utils.js, package.json, test/document-test.js
Includes a test that fails before the change in util.js is applied
example/example.js fails when run without this change
=> signature validation fails if node passed to loadSignature is a Document

lib/exclusive-canonicalization.js, test/canonicalization-unit-tests.js
Testing against a major SAML implementation, I found that some implementations of the XML Signature Syntax and Processing Version 2.0 spec expect that `xmlns:ds` will have a default value of `http://www.w3.org/2000/09/xmldsig#`
xml-crypto was defaulting the missing value to `xmlns:ds=""`, which broke the hash calculation.
=> xmlns:ds should default to http://www.w3.org/2000/09/xmldsig# if not provided

lib/signed-xml.js, lib/utils.js, test/canonicalization-unit-tests.js, test/signature-integration-tests.js, test/static/signature_with_inclusivenamespaces_lines.xml, test/static/signature_with_inclusivenamespaces_lines_windows.xml
Convert `\r\n` new lines to canonical form: `\n`.
Convert multiple new lines to a single one.
Fixes #65 & probably #43.
=> Canonicalization of line separators

lib/exclusive-canonicalization.js, lib/utils.js, test/c14nWithComments-unit-tests.js, test/canonicalization-unit-tests.js
This is an attempt to fix several issues related to the canocalization of special characters. This fixes #28.
See:
- https://www.w3.org/TR/xml-c14n#ProcessingModel (Attribute Nodes, Text Nodes)
- https://www.w3.org/TR/xml-c14n#Example-Chars
Note: when checking the documentation of c14n or xml, it is very important to make sure you are viewing the latest version. It can happen quite easily that you are reading an outdated spec.
Pinging @cmordue @yaronn @bjrmatos
=> Fixed normalization of special characters according to spec

README.md
This is a fix for the example signature validation documentation; the toString() call on the signature node turns out to be harmful, as it removes namespace metadata which would otherwise propagate from the parent document. In situations where the namespace is `ds`, this works out ok (as ds is provided as a default) but when using other strings for this namespace the example boilerplate fails.
In the example below, the definition of `dsig` would be undefined in a toString-orphaned signature, and the canonicalization algorithm would resolve the url as an empty string -- changing the underlying canonical text and causing the SignatureValue verification to fail.
```
<samlp:Response ... xmlns:dsig="http://www.w3.org/2000/09/xmldsig#">
...
<dsig:Signature>
<dsig:SignedInfo> …
```
=> Remove namespace-breaking reserialization of signature from example in README

lib/exclusive-canonicalization.js, test/canonicalization-unit-tests.js
To allow namespace overriding in c14n.
We have a case in SAML response verification where the server sends XML with the same namespace prefix (ds) overridden on an inner element to a different URI, extract from actual sample attached. 
[namespace_override.txt](https://github.com/yaronn/xml-crypto/files/461722/namespace_override.txt)
=> Separate namespaces with same prefix but different URI

README.md, lib/c14n-canonicalization.js, lib/signed-xml.js, package.json, test/c14n-non-exclusive-unit-test.js
This is a patch proposal for issues regarding to non-exclusive c14n handling bug.
This PR contains README update and corresponding unit test specs.
Issues relating:
https://github.com/yaronn/xml-crypto/issues/113
https://github.com/yaronn/xml-crypto/issues/153
It was so painful to write code to be compatible with Node.js 0.10.
Give me a praise... :tired_face:
As you know, there is a quick-patch in `lib/signed-xml.js` as below.  
```
//***workaround for validating windows mobile store signatures - it uses c14n but does not state it in the transforms
if (!hasImplicitTransforms && transforms.length==1 && transforms[0]=="http://www.w3.org/2000/09/xmldsig#enveloped-signature")
transforms.push("http://www.w3.org/2001/10/xml-exc-c14n#")
```
I found that there are a lot of signed XML in the world …
=> Patch for non exclusive c14n

lib/enveloped-signature.js, lib/signed-xml.js
This patch really makes sure that we only cut out the signature in which our enveloped signature transformation is defined. For the moment this is based on the signature value...
=> fix for enveloped signatures

lib/signed-xml.js, test/signature-unit-tests.js
When computing the signature, ancestor namespaces of SignedInfo and
reference node were not passed into the 'getCanonXml' method like
they are during signature verification
This attempts to fix #164
=> Fix canon xml being computed differently when signing, than when verfying

lib/utils.js, test/c14nWithComments-unit-tests.js, test/canonicalization-unit-tests.js
Fixes https://github.com/yaronn/xml-crypto/issues/195
=> Fixes line end and white space normalization.

lib/signed-xml.js
Easier async integration in other projects when using built in sign/verify algorithms
=> Async response for built in algo sign/verify

README.md, example/example.js, lib/signed-xml.js, package-lock.json, package.json, test/c14n-non-exclusive-unit-test.js, test/c14nWithComments-unit-tests.js, test/canonicalization-unit-tests.js, test/document-test.js, test/hmac-tests.js, test/saml-response-test.js, test/signature-integration-tests.js, test/signature-unit-tests.js, test/wsfed-metadata-test.js
The package is now scoped under @xmldom. See https://github.com/xmldom/xmldom/pull/278
This fixes security vulnerability CVE-2021-32796
Fixes #234
=> Update xmldom to 0.7.0

lib/c14n-canonicalization.js, test/c14n-non-exclusive-unit-test.js
Hey there! I wanted to start by saying thank you for the hard work maintaining this package.
I've been running into problems related to mismatched signature digests when validating a signed XML document, and I've narrowed the mismatch down to differences in how this library and another canonicalize the document. While the real world example involves SAML response XML, I've tried to instead demonstrate the behavior with a minimal failing test.
For the `http://www.w3.org/TR/2001/REC-xml-c14n-20010315` method, I noticed that `xml-crypto` seems to be repeating namespaces that are already defined on an ancestor node.
If we start with this document...
```xml
<root xmlns:aaa='bbb'>
<child1>
<child2>
<child3 aaa:foo='bar'>
</child3>
</child2>
</child1>
</root>
```
...and like in the test, …
=> Correct behavior for XML canonicalization with namespaces and nested elements

package-lock.json, package.json
Hey - I'm not sure how you'd want to handle this, but the vuln fix that caused the @xmldom/xmldom breaking change was backported into 0.7.6 - https://github.com/xmldom/xmldom/releases/tag/0.7.6
Would you mind cutting a 2.x release for those of us not in a position to handle breaking changes?
=> 2.1.5: bump @xmldom/xmldom to 0.7.9

lib/signed-xml.js
Hello @cjbarth, @LoneRifle, @yaronn,
I have added implementation for getKeyInfo function, please check if it looks good, then I'll proceed with unit tests.   
I am getting confused with below line of codes,
For FileKeyInfo, I'm assuming it accepts file which will be public X509 certificate and this.getKeyInfo function will return the X509Data. **But, what is the use of this.getKey()??** I'm assuming it will return public certificate. But, in some places it used as privateKey, as shown in below statements,
In node-saml->src->xml.ts->signXml, signingKey gets the privateKey value assigned, as shown below,
However, in xml-crypto->lib->signed-sml.js, signingKey gets the value from KeyInfoProvider.getKey(this.keyInfo) which looks to be public certificate..
Can you please help me to clear this..
=> Updated getKeyInfo function with actual implementation

lib/file-key-info.js, lib/signed-xml.js, lib/string-key-info.js, test/document-test.js
The type definitions for this awesome library require that the value of `SignedXML.keyInfoProvider` be an instance of `FileKeyInfo`, but the methods on FileKeyInfo belong to the instance itself and not the prototype. This issue is only strictly a problem for TypeScript, but this change has a beneficial affect (in terms of reuse) on NodeJS clients, as well, and this is a non-breaking change. 
Also adding some documentation to the methods to clear up some of the confusion. Feedback is welcome!
Closes #272
=> make FileKeyInfo extensible for compatibility with TypeScript

index.d.ts, package.json
- port type declaration from @DefinitelyTyped, and reference it from package.json
- add definitions for KeyInfo, StringKeyInfo, tweak SignedXml to take a KeyInfo for `keyInfoProvider` instead of FileKeyInfo
=> feat: add type declaration

index.d.ts, lib/signed-xml.js, test/signature-unit-tests.js
Currently, the `inclusiveNamespacesPrefixList` property on the Reference interface is only used during loading of references.
This change would allow the use of the same property during the creation of references to add a `InclusiveNamespaces` element.
Example:
```
sig.addReference(
"//*[local-name(.)='Timestamp']",
["http://www.w3.org/2001/10/xml-exc-c14n#"],
'http://www.w3.org/2000/09/xmldsig#sha1',
'','',
'wsse soapenc soapenv xsd xsi');
```
Result:
```
<ds:Reference URI="#TS-b3f4bfa7-fe3b-4ee1-aa8c-289ee7de442b">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
<InclusiveNamespaces PrefixList="wsse soapenc soapenv xsd xsi"
xmlns="http://www.w3.org/2001/10/xml-exc-c14n#"/>
</ds:Transform>
</ds:Transforms>
<ds:DigestMethod …
```
=> Use inclusiveNamespacesPrefixList to generate InclusiveNamespaces

index.d.ts, lib/signed-xml.js, test/signature-unit-tests.js
Added a new optional property, attrs, to the KeyInfo interface.
The attrs property is an object that holds key-value pairs representing the attributes and their corresponding values. 
When present, these attributes will be appended to the KeyInfo element during XML generation.
Example:
```
sig.keyInfoProvider = {
getKeyInfo: () => {
return `<wsse:SecurityTokenReference xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="STR-${securityTokenReferenceGuid}">`
+ `<wsse:Reference URI="#X509-${randomUUID()}" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3"/>`
+ `</wsse:SecurityTokenReference>`
}, …
```
=> Add support for appending attributes to KeyInfo element

.eslintrc.json, .vscode/settings.json, README.md, example/example.js, index.d.ts, index.js, lib/c14n-canonicalization.js, lib/enveloped-signature.js, lib/exclusive-canonicalization.js, lib/file-key-info.js, lib/signed-xml.js, lib/string-key-info.js, lib/utils.js, test/c14n-non-exclusive-unit-test.js, test/c14nWithComments-unit-tests.js, test/canonicalization-unit-tests.js, test/document-test.js, test/hmac-tests.js, test/saml-response-test.js, test/signature-integration-tests.js, test/signature-unit-tests.js, test/wsfed-metadata-test.js, test/xml-assert.js
This is a collection of automatic code format changes from running `npm run prettier-format`. There are just a few changes in `example.js` and `README.md` that were manual (to disable rules and add code fences).
=> Format code

.github/workflows/ci.yml, package-lock.json, package.json
This is a `semver-major` change that will bring the dependencies up to supported versions and more easily allow migration of tests to supported test frameworks.
=> Target an LTS version of Node

.eslintrc.json
This PR aims to improve code quality and consistency by tightening up some linting rules slightly. These rules require Node >=4 because of the rule to prefer `let` over `var`.
=> Make linting rules more strict

.eslintrc.json, lib/c14n-canonicalization.js, lib/enveloped-signature.js, lib/exclusive-canonicalization.js, lib/signed-xml.js, lib/utils.js, package.json, test/signature-integration-tests.js, test/signature-unit-tests.js
The new linting rules left the linting test not passing. This changes one rule to a warning and makes a few small changes to avoid another rule failure.
=> Lint code for new linting rules

.nycrc.json
The wrong path was used for the configuration of `nyc`, so a blank report was being generated.
=> Use correct path for code coverage reports

index.d.ts, lib/hash-algorithms.js, lib/signature-algorithms.js, lib/signed-xml.js, lib/utils.js, test/c14n-non-exclusive-unit-test.js
This moves some code around so that classes, or closely related classes, are in their own files.
=> Refactor classes into their own files

.eslintrc.json, lib/c14n-canonicalization.js, lib/exclusive-canonicalization.js, test/hmac-tests.js
- Flag `no-unused-vars` violations as errors
- Remove spurious import in HMAC tests
- Remove spurious namespace arg to `renderAttrs()`
=> Enforce eslint `no-unused-vars`

.gitignore, lib/c14n-canonicalization.js, lib/utils.js, test/c14n-non-exclusive-unit-test.js
=> fix issue in case when namespace has no prefix

package.json
Closes #332
> If you are in a position to help get that fixed for the 3.x branch, a PR is welcome as we are soon to release 3.2.
@cjbarth is it alright???
=> Ignore unnecessary files in the release

index.js
Closes #331
This allow us to do
```ts
const C14nCanonicalization = require('xml-crypto').C14nCanonicalization 
const ExclusiveCanonicalization= require('xml-crypto').ExclusiveCanonicalization
// Use Example 
const DOMParser = require("@xmldom/xmldom").DOMParser
let xml_string = '<root><child>123</child></root>'
let documentElement= (new DOMParser()).parseFromString(xml_string).documentElement
// C14nCanonicalization
console.log( (new C14nCanonicalization()).process(documentElement, {}).toString() )
// ExclusiveCanonicalization
console.log( (new ExclusiveCanonicalization()).process(documentElement, {}).toString() )
```
This is not a breaking change
Any correction I will try to correct immediately
=> Exports C14nCanonicalization, ExclusiveCanonicalization

package.json
Fix for https://github.com/node-saml/xml-crypto/pull/334
=> Fix missing `index.js` on release

src/c14n-canonicalization.ts, src/enveloped-signature.ts, src/exclusive-canonicalization.ts, src/hash-algorithms.ts, src/index.ts, src/signature-algorithms.ts, src/signed-xml.ts, src/utils.ts, test/c14n-non-exclusive-unit-tests.spec.ts, test/c14nWithComments-unit-tests.spec.ts, test/canonicalization-unit-tests.spec.ts, test/document-tests.spec.ts, test/hmac-tests.spec.ts, test/key-info-tests.spec.ts, test/saml-response-tests.spec.ts, test/signature-integration-tests.spec.ts, test/signature-unit-tests.spec.ts, test/utils-tests.spec.ts, test/wsfed-metadata-tests.spec.ts
Please, @LoneRifle and @shunkica, feel free to push to this branch, or create a PR against it if you can't push, as often as you'd like to help get this done more quickly.
=> Convert this project to TypeScript

src/signed-xml.ts
In the examples it is shown that the value can be read. Therefore, the value should not be marked as private.
=> Fix validationErrors type

src/exclusive-canonicalization.ts, src/signed-xml.ts, src/utils.ts
`findChilds()` isn't the grammatically correct way to say this. It was renamed `findChildren()`, deprecating the old method, which can then be removed in vNext.
=> Rename `findChilds()` to `findChildren()`

README.md, src/signed-xml.ts, src/types.ts, src/utils.ts, test/signature-integration-tests.spec.ts, test/signature-unit-tests.spec.ts
The current recommendation is to have consumers check IDs on elements. We already do this internally, with much more rigor than the README suggests. This PR adds a method to leverage internal methods to perform a more rigorous check of signing of elements the consumer would like to use.
=> Add method for checking if element is signed

src/signed-xml.ts
The validation logic was a little convoluted. This PR aims to clean up that logic a little to make it easier to reason on. The deprecated functions can be removed in the next major release.
=> Improve and simplify validation logic

src/signed-xml.ts, test/c14nWithComments-unit-tests.spec.ts, test/canonicalization-unit-tests.spec.ts
During a refactor, a bug was introduced that caused inconsistent processing of transforms. This PR fixes this inconsistency and adds a check to make sure that another inconsistency, that of trying to transform a string, isn't introduced. Ideally, the `xpath` library would throw if a `string` is passed instead of a `Node`, which would solve this problem.
This addresses an issue observed by @srd90 in the bottom part of his comment [here](https://github.com/node-saml/xml-crypto/issues/378#issuecomment-1687120300).
=> Enforce consistent transform processing

src/c14n-canonicalization.ts, src/enveloped-signature.ts, src/exclusive-canonicalization.ts, src/signed-xml.ts, test/c14nWithComments-unit-tests.spec.ts, test/canonicalization-unit-tests.spec.ts, test/signature-unit-tests.spec.ts, test/static/invalid_signature_without_transforms_element.xml, test/static/valid_signature_without_transforms_element.xml
There was a bug introduced in the 4.x release of `xml-crypto` whereby transforms weren't added in all the cases they were supposed to.
This includes code from the [comment](https://github.com/node-saml/xml-crypto/issues/378#issuecomment-1687120300) by @srd90.
Closes #378
=> Fix transform processing regression

package-lock.json, package.json, src/c14n-canonicalization.ts, src/enveloped-signature.ts, src/exclusive-canonicalization.ts, src/signed-xml.ts, src/utils.ts, test/c14n-non-exclusive-unit-tests.spec.ts, test/c14nWithComments-unit-tests.spec.ts, test/canonicalization-unit-tests.spec.ts, test/document-tests.spec.ts, test/hmac-tests.spec.ts, test/key-info-tests.spec.ts, test/saml-response-tests.spec.ts, test/signature-integration-tests.spec.ts, test/signature-unit-tests.spec.ts, test/wsfed-metadata-tests.spec.ts
In order to improve code quality, type checking, and runtime resilience, checking the existence and type of DOM node that is bring processed has been consolidated around the `is-dom-node` library.
=> Use is-dom-node for DOM node checking and narrowing

src/signed-xml.ts, src/types.ts
Every method was public, but wasn't designed to be. Methods that weren't used in tests are marked as private in this PR.
=> Reduce public interface by making some methods private

README.md, src/signed-xml.ts, test/signature-unit-tests.spec.ts
The `references` array is a little sensitive to what is in it, we don't want people mutating it without the accessors.
=> Make references accessible only via get/set

README.md, src/signed-xml.ts, src/types.ts, test/hmac-tests.spec.ts, test/saml-response-tests.spec.ts
Validation errors were class-wide making it unnecessarily difficult to match an error with the reference that caused it. This PR moves those errors to the `reference` on which they occurred.
Additionally, the validation error for a `checkSignature()` was changed to throw instead of adding to a global `validationErrors` object.
=> Move validation messages to each reference

src/signed-xml.ts, test/document-tests.spec.ts
The `validateReferences()` function is no longer being used as of #395, so it is removed here.
Some other areas of the code has unnecessarily complex code; this was simplified.
=> Improve code clarity; remove unused functions

README.md, src/signed-xml.ts, src/types.ts, test/document-tests.spec.ts, test/signature-unit-tests.spec.ts
Previously, the API for checking if a reference was valid was very complex. This adds support for allow for a single method call on the container that represents the reference to determine if it passed validation. The idea is that this can clean up some code as found at `node-saml`:
```typescript
export const validateXmlSignatureForCert = (
signature: Node,
certPem: string,
fullXml: string,
currentNode: Element
): boolean => {
const sig = new xmlCrypto.SignedXml();
sig.keyInfoProvider = {
file: "",
getKeyInfo: () => "<X509Data></X509Data>",
getKey: () => Buffer.from(certPem),
};
sig.loadSignature(signature);
// We expect each signature to contain exactly one reference to the top level of the xml we
//   are validating, so if we see anything else, reject.
if (sig.references.length != 1) …
```
=> Add support for directly querying a node to see if it has passed validation

src/signed-xml.ts, test/signature-unit-tests.spec.ts
Creating a signature using the default `getKeyInfoContent` function was missing prefixes on the `X509Certificate` tags, e.g.:
```
...
<ds:KeyInfo>
<ds:X509Data> 
<X509Certificate>MII...</X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
...
```
This PR should fix that. I modified an existing test to stop stubbing out the default `getKeyInfoContent` so that the existing behavior broke that test, then validated that the new behavior causes it to pass.
=> Ensure the X509Certificate tag is properly prefixed

README.md, src/c14n-canonicalization.ts, src/enveloped-signature.ts, src/exclusive-canonicalization.ts, src/signed-xml.ts, src/types.ts, test/hmac-tests.spec.ts, test/key-info-tests.spec.ts, test/signature-integration-tests.spec.ts, test/signature-unit-tests.spec.ts
This removes the default canonicalization algorithm forcing the consumer to choose the one that they want. This is an attempt to address #376.
Side note: We do not support all the "required" algorithms. See: https://www.w3.org/TR/xmldsig-core1/#:~:text=4.1%20DSA%5D-,canonicalization,-Required
=> Remove default canonicalization algorithm

README.md, src/signed-xml.ts, test/hmac-tests.spec.ts, test/key-info-tests.spec.ts, test/signature-integration-tests.spec.ts, test/signature-unit-tests.spec.ts
This removes the default digest algorithm forcing the consumer to choose the one that they want. This is an attempt to address https://github.com/node-saml/xml-crypto/issues/376.
=> Remove default for digest algorithm

README.md, src/signed-xml.ts, test/key-info-tests.spec.ts, test/signature-integration-tests.spec.ts, test/signature-unit-tests.spec.ts
This removes the default signature algorithm forcing the consumer to choose the one that they want. This is an attempt to address https://github.com/node-saml/xml-crypto/issues/376.
=> Remove default for signature algorithm

README.md, src/signed-xml.ts, test/hmac-tests.spec.ts, test/key-info-tests.spec.ts, test/signature-integration-tests.spec.ts, test/signature-unit-tests.spec.ts
This removes the default transformation algorithm, forcing the consumer to choose the one that they want. This is an attempt to address https://github.com/node-saml/xml-crypto/issues/376.
I've also reviewed the README to update a few things that were missed in previous PR removing defaults.
=> Remove default for transformation algorithm

README.md, src/signed-xml.ts, test/key-info-tests.spec.ts, test/signature-unit-tests.spec.ts
Per the discussion [here](https://github.com/node-saml/xml-crypto/discussions/399#discussioncomment-7264750), remove the default for `getKeyInfoContent`. This will force the consumer to make a decision here. The default implementation is still available.
=> Remove the default for `getKeyInfoContent` forcing a consumer to choose

src/signed-xml.ts, test/document-tests.spec.ts, test/key-info-tests.spec.ts, test/signature-unit-tests.spec.ts
`getKeyInfoContent` was incorectly set to `noop` instead of `getCertFromKeyInfo`
=> Set `getCertFromKeyInfo` to `noop`
